on:
  push:
    tags:
      - 'v*'

name: 🚀 Release

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Compile code
        run: pnpm run build

      - name: Publish
        run: pnpm publish --access=public --no-git-checks

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
